sudo: false

language: Python
python:
  - "2.7"

install:
  # Install conda
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes yes --set changeps1 no
  - conda update conda
  - conda create -n test-environment python=$TRAVIS_PYTHON_VERSION pandas numpy
  - source activate test-environment
  - conda install --file conda-requirements.txt # xlrd, possibly others
  - export BTAX_OUT_DIR=btax_output_dir # make an output dir
  - mkdir btax_output_dir
  - python setup.py install

script:
  - run-btax                    # ensure the pickles are updated
  - python btax/check_output.py # check pickles
